modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="xiaoou6630"
description='''
An addon for Create Villager Labor. Left-click a seated worker with a Lead, or ring a Bell nearby, to apply the "Work!" effect. Workers with the effect perform basin recipes instantly, but finished items may be destroyed (configurable chance).
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0.0,6.1.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create_labor"
    type="required"
    versionRange="[1.4.0,1.5.0)"
    ordering="AFTER"
    side="BOTH"
